baseURL = "https://iamrobots.com/"
title = "I am robots"
author = "David Lively"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "I am robots"
  disableWebFonts = false

[[menu.main]]
    name = "About"
    url  = "/about/iamrobots"
[[menu.main]]
    name = "Resume"
    url  = "/files/david-lively-resume.pdf"
[[menu.main]]
    name = "Github"
    url  = "https://github.com/iamrobots"
# [[menu.main]]
#     name = "Projects"
#     url  = "/projects"